# Generated by Django 6.1.1 on 2026-10-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clockin_time', models.DateTimeField()),
                ('clockout_time', models.DateTimeField()),
            ],
            options={
                'ordering': ['-clockin_time'],
            },
        ),
    ]
