# Generated by Django 6.1.1 on 2026-10-05 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_100days', '0003_studysession_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
